### ISSUE TITLE
FFaField requires some special traits for std::array

### ISSUE THREAD

**Issue by sanguinariojoe** [SAP/fedem-foundation#9]
I needed to add the following streaming traits at https://github.com/SAP/fedem-foundation/blob/main/src/FFaLib/FFaContainers/FFaField.H#L24:

```
template <typename T, size_t N>
std::ostream& operator<<(std::ostream& stream, const std::array<T, N>& v)
{
  for (unsigned int i = 0; i < N - 1; i++)
    stream << v.at(i) << ",";
  stream << v.at(N - 1);
  return stream;
}

template <typename T, size_t N>
std::istream& operator>>(std::istream& stream, std::array<T, N>& v)
{
  char tmp;
  for (unsigned int i = 0; i < N - 1; i++)
    stream >> v.at(i) >> tmp;
  stream >> v.at(N - 1);
  return stream;
}
```

So I can deal with [this](https://github.com/SAP/fedem-mdb/blob/main/vpmDB/FmGraph.H#L112), which has the type defined [here](https://github.com/SAP/fedem-mdb/blob/main/vpmDB/FmGraph.H#L25)

Probably the smartest solution is creating a new type on the same fashion than [FFaByteArray](https://github.com/SAP/fedem-foundation/blob/main/src/FFaLib/FFaContainers/FFaByteArray.H)

**Comment by kmoks** [comment]
Thanks for reporting these issues, @sanguinariojoe. May I ask what compiler/version you are using?

The fix you suggest here should not be necessary, as we already have the [FmArray.H](https://github.com/SAP/fedem-mdb/blob/main/vpmDB/FmArray.H) file containing similar definitions, except we there specialize for type `int` instead of the template parameter `T`. This file is then included in FmGraph.H such that the `FFaField` member then should work. And it compiles fine with gcc 7.5 (Ubuntu 18.04) to gcc 11.4 (Ubuntu 22.04) as well as on Visual Studio 2019 with its integrated C++ compiler.

Will it resolve your issue to just change the FmArray.H header accordingly in the fedem_mdb repo?

Another note on your suggestion: You here use comma ',' as separator between the values, whereas we (in FmArray.H) have used a space. Your version will therefore break (probably) when trying to read existing model files having space as separators.

**Comment by sanguinariojoe** [comment]
Oh, i did not realiced on fmarray. My bad...

Then it is probably a problem on the order the includes are placed. I
already reported a similar problem with bytesarray on another issue.

I have to take my baby to the kindergarden now. But later i am checking and
giving you feedback (including compiler and so on)

**Comment by sanguinariojoe** [comment]
Yeah, the solution is swapping a couple of includes:

```
#include "vpmDB/FmArray.H"
#include "vpmDB/FmResultBase.H"
```

at https://github.com/SAP/fedem-mdb/blob/main/vpmDB/FmGraph.H#L11 , and

```
#include "vpmDB/FmGraph.H"
#include "vpmDB/FmCurveSet.H"
```

at https://github.com/SAP/fedem-mdb/blob/main/vpmDB/FmGraph.C#L13

---

> May I ask what compiler/version you are using?

My compiler is "gcc version 13.2.1 20230801 (GCC)", with "glibc 2.38".

> Another note on your suggestion: You here use comma ',' as separator between the values, whereas we (in FmArray.H) have used a space. Your version will therefore break (probably) when trying to read existing model files having space as separators.

It mostly sure breaks, but I do not think the separator will be the problem, as long as the reader is agnostic to that (it would work with every single-char separator).

Maybe if one changes the locale nasty things might happens... Probably with your version also...

**Comment by kmoks** [comment]
Thanks for quick reply. That's great, I'll just swap those headers then.

> but I do not think the separator will be the problem, as long as the reader is agnostic to that (it would work with every single-char separator).

Not sure about this, think in year case the `stream >> v.at(i) >> tmp` will eat the second value (or the first digit of it) in the `tmp` variable when reading a file with space as separators? So unless you have other good reason to introduce comma-separators I think I stick with spaces, for the sake of backward compatibility.

So you are using a newer gcc version that we have tried so far. Our experience is that newers versions tend to get more and more strict to adhere to the coding standards (which is good). But then of course there might be some porting work like this before everything runs.

Also note, we have not built the gui part (the fedem-gui repo) with gcc on Linux in a very long time (not since with Ubuntu 16.04), so don't be surprised if there are a lot of issues there (like you already found a few of).

**Comment by sanguinariojoe** [comment]
> So unless you have other good reason to introduce comma-separators I think I stick with spaces

Absolute! Please, go ahead with the spaces. No interest on commas at all

> Also note, we have not built the gui part (the fedem-gui repo) with gcc on Linux in a very long time (not since with Ubuntu 16.04), so don't be surprised if there are a lot of issues there (like you already found a few of).

Let's sail those water together then! :-p
